# Generated by Django 5.1.4 on 2025-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_contactmessage_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactform',
            new_name='ContactMessage',
        ),
    ]
