# Generated by Django 5.1.4 on 2025-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_contactform_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CL', 'Cleanser'), ('SE', 'Serum'), ('FO', 'Face Oil'), ('SS', 'SunScreen'), ('MZ', 'Moisturizer'), ('TR', 'Toner'), ('FM', 'Face Mask'), ('EC', 'Eye Cream'), ('FW', 'Face Wash'), ('SP', 'Setting Spray'), ('CC', 'Concealer'), ('PR', 'Primer'), ('BW', 'Body Wash'), ('BS', 'Body Scrub'), ('BL', 'Body Lotion'), ('BO', 'Body Oil'), ('BS', 'Body Serum'), ('BG', 'Body Gel'), ('BC', 'Body Cleanser'), ('SG', 'Shower Gel'), ('SP', 'Shampoo'), ('CT', 'Conditioner'), ('HM', 'Hair Mask'), ('HC', 'Hair Color'), ('HO', 'Hair Oil'), ('HS', 'Hair Spray'), ('DS', 'Dry Shampoo'), ('HD', 'Hair Detangler'), ('HC', 'Hair Cream'), ('HW', 'Hair Wax'), ('PM', 'Primer'), ('FD', 'Foundation'), ('CL', 'Concealer'), ('PD', 'Powder'), ('BS', 'Blush'), ('BZ', 'Bronzer'), ('HL', 'Highlighter'), ('ES', 'Eye Shadow'), ('EL', 'Eyeliner'), ('MS', 'Mascara'), ('LB', 'Lip Balm'), ('LS', 'Lipstick'), ('LG', 'Lip Gloss'), ('SR', 'Setting Spay')], max_length=50)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
