# Generated by Django 5.1.4 on 2025-02-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FC', 'FACE'), ('BY', 'BODY'), ('HI', 'HAIR'), ('MU', 'MAKEUP')], max_length=50),
        ),
    ]
