# Generated by Django 5.1.4 on 2025-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Cleanser'), ('SM', 'Serum'), ('FO', 'Face Oil'), ('SS', 'SunScreen'), ('MZ', 'Moisturizer'), ('TR', 'Toner'), ('FM', 'Face Mask'), ('EC', 'Eye Cream'), ('FW', 'Fash Wash'), ('SP', 'Setting Spray'), ('CR', 'Concealer'), ('PM', 'Primer'), ('BW', 'Body Wash'), ('BS', 'Body Scrub'), ('BL', 'Body Lotion'), ('BO', 'Body Oil'), ('BE', 'Body Serum'), ('BG', 'Body Gel'), ('BC', 'Body Concealer'), ('SG', 'Shower Gel'), ('SH', 'Shampoo'), ('CD', 'Conditioner'), ('HM', 'Hair Mask'), ('HC', 'Hair Color'), ('HO', 'Hair Oil'), ('HS', 'Hair Spray'), ('DS', 'Dry Shampoo'), ('HD', 'Hair Detangler'), ('HE', 'Hair Cream'), ('HW', 'Hair Wax'), ('PR', 'Primer'), ('FD', 'Foundation'), ('CR', 'Concealer'), ('PR', 'Powder'), ('BU', 'Blush'), ('BZ', 'Bronzer'), ('HG', 'Highlighter'), ('ES', 'Eye Shadow'), ('EL', 'Eyeliner'), ('MS', 'Mascara'), ('LB', 'Lip Balm'), ('LS', 'Lipstick'), ('LG', 'Lip Gloss'), ('SP', 'Setting Spray')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
