# Generated by Django 5.1.4 on 2025-02-22 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_payment_orderplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPlace',
            new_name='OrderPlaced',
        ),
    ]
